version: '2'
services:
    iquitosapp-app:
        image: iquitosapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iquitosapp-mysql:3306/iquitosapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://iquitosapp-elasticsearch:9200
        ports:
            - 8080:8080
    iquitosapp-mysql:
        extends:
            file: mysql.yml
            service: iquitosapp-mysql
    iquitosapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iquitosapp-elasticsearch
